// <auto-generated />
using System;
using BuildHub;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuildHub.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BuildHub.Models.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("nameAr")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("nameEn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("parentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("categoryId");

                    b.HasIndex("parentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BuildHub.Models.Contract", b =>
                {
                    b.Property<int>("contractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("contractId"));

                    b.Property<string>("paymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("quoteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("signedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("contractId");

                    b.HasIndex("quoteId")
                        .IsUnique();

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("BuildHub.Models.EscrowTransaction", b =>
                {
                    b.Property<int>("escrowTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("escrowTransactionId"));

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("contractId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("heldAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("milestoneId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("releasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("escrowTransactionId");

                    b.HasIndex("contractId");

                    b.HasIndex("milestoneId")
                        .IsUnique()
                        .HasFilter("[milestoneId] IS NOT NULL");

                    b.ToTable("EscrowTransactions");
                });

            modelBuilder.Entity("BuildHub.Models.Milestone", b =>
                {
                    b.Property<int>("milestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("milestoneId"));

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("contractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("orderIndex")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("milestoneId");

                    b.HasIndex("contractId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("BuildHub.Models.Notification", b =>
                {
                    b.Property<int>("notificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("notificationId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("notificationId");

                    b.HasIndex("userId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BuildHub.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("currentPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("vendorProfileId")
                        .HasColumnType("int");

                    b.HasKey("productId");

                    b.HasIndex("categoryId");

                    b.HasIndex("vendorProfileId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BuildHub.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BuildHub.Models.Quote", b =>
                {
                    b.Property<int>("quoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("quoteId"));

                    b.Property<int>("durationDays")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("quoteRequestId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("submittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("vendorProfileId")
                        .HasColumnType("int");

                    b.HasKey("quoteId");

                    b.HasIndex("quoteRequestId");

                    b.HasIndex("vendorProfileId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("BuildHub.Models.QuoteNegotiation", b =>
                {
                    b.Property<int>("quoteNegotiationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("quoteNegotiationId"));

                    b.Property<int>("QuoteId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("createIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("proposedDurationDays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("proposedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("quoteNegotiationId");

                    b.HasIndex("QuoteId");

                    b.HasIndex("UserId");

                    b.ToTable("QuoteNegotiations");
                });

            modelBuilder.Entity("BuildHub.Models.QuoteRequest", b =>
                {
                    b.Property<int>("qutoeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("qutoeRequestId"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("projectId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("visibilityType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("qutoeRequestId");

                    b.HasIndex("categoryId");

                    b.HasIndex("projectId");

                    b.ToTable("QuoteRequests");
                });

            modelBuilder.Entity("BuildHub.Models.QuoteRequestInvite", b =>
                {
                    b.Property<int>("inviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("inviteId"));

                    b.Property<string>("inviteStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("quoteRequestId")
                        .HasColumnType("int");

                    b.Property<int>("vendorProfileId")
                        .HasColumnType("int");

                    b.HasKey("inviteId");

                    b.HasIndex("quoteRequestId");

                    b.HasIndex("vendorProfileId");

                    b.ToTable("QuoteRequestInvites");
                });

            modelBuilder.Entity("BuildHub.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int?>("VendorProfileId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ContractId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("VendorProfileId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BuildHub.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BuildHub.Models.VendorProfile", b =>
                {
                    b.Property<int>("VendorProfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorProfileID"));

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsVerfied")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VendorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VendorProfileID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("VendorProfiles");
                });

            modelBuilder.Entity("BuildHub.Models.Category", b =>
                {
                    b.HasOne("BuildHub.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("parentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("BuildHub.Models.Contract", b =>
                {
                    b.HasOne("BuildHub.Models.Quote", "quote")
                        .WithMany()
                        .HasForeignKey("quoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("quote");
                });

            modelBuilder.Entity("BuildHub.Models.EscrowTransaction", b =>
                {
                    b.HasOne("BuildHub.Models.Contract", "Contract")
                        .WithMany("EscrowTransactions")
                        .HasForeignKey("contractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildHub.Models.Milestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("milestoneId");

                    b.Navigation("Contract");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("BuildHub.Models.Milestone", b =>
                {
                    b.HasOne("BuildHub.Models.Contract", "Contract")
                        .WithMany("Milestones")
                        .HasForeignKey("contractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("BuildHub.Models.Notification", b =>
                {
                    b.HasOne("BuildHub.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildHub.Models.Product", b =>
                {
                    b.HasOne("BuildHub.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildHub.Models.VendorProfile", "vendorProfile")
                        .WithMany("Products")
                        .HasForeignKey("vendorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("vendorProfile");
                });

            modelBuilder.Entity("BuildHub.Models.Project", b =>
                {
                    b.HasOne("BuildHub.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildHub.Models.Quote", b =>
                {
                    b.HasOne("BuildHub.Models.QuoteRequest", "QuoteRequest")
                        .WithMany()
                        .HasForeignKey("quoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildHub.Models.VendorProfile", "VendorProfile")
                        .WithMany("Quotes")
                        .HasForeignKey("vendorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuoteRequest");

                    b.Navigation("VendorProfile");
                });

            modelBuilder.Entity("BuildHub.Models.QuoteNegotiation", b =>
                {
                    b.HasOne("BuildHub.Models.Quote", "Quote")
                        .WithMany()
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildHub.Models.User", "User")
                        .WithMany("QuoteNegotiations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quote");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildHub.Models.QuoteRequest", b =>
                {
                    b.HasOne("BuildHub.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildHub.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("projectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BuildHub.Models.QuoteRequestInvite", b =>
                {
                    b.HasOne("BuildHub.Models.QuoteRequest", "QuoteRequest")
                        .WithMany()
                        .HasForeignKey("quoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildHub.Models.VendorProfile", "VendorProfile")
                        .WithMany("QuoteRequestInvites")
                        .HasForeignKey("vendorProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuoteRequest");

                    b.Navigation("VendorProfile");
                });

            modelBuilder.Entity("BuildHub.Models.Review", b =>
                {
                    b.HasOne("BuildHub.Models.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId");

                    b.HasOne("BuildHub.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("BuildHub.Models.User", "Reviewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuildHub.Models.VendorProfile", "VendorProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("VendorProfileId");

                    b.Navigation("Contract");

                    b.Navigation("Product");

                    b.Navigation("Reviewer");

                    b.Navigation("VendorProfile");
                });

            modelBuilder.Entity("BuildHub.Models.VendorProfile", b =>
                {
                    b.HasOne("BuildHub.Models.User", "User")
                        .WithOne("VendorProfile")
                        .HasForeignKey("BuildHub.Models.VendorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BuildHub.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("BuildHub.Models.Contract", b =>
                {
                    b.Navigation("EscrowTransactions");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("BuildHub.Models.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Projects");

                    b.Navigation("QuoteNegotiations");

                    b.Navigation("Reviews");

                    b.Navigation("VendorProfile");
                });

            modelBuilder.Entity("BuildHub.Models.VendorProfile", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("QuoteRequestInvites");

                    b.Navigation("Quotes");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
